"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['data']
OPTIONS = {
    'iconfile': 's3_uploader_icon.icns',
    'argv_emulation': True,
    'includes': 'HTMLParser,ConfigParser,boto3,botocore,boto3.s3.inject'
}

setup(
    name="S3Uploader",
    version="1.0",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
